version: "3.8"
services:
  database1:
    build: ./docker/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: default
  organizzare-back:
    build: .
    depends_on:
      - database1
    ports:
      - "5000:5000"