version: "3"

services:
  database1:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: default
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/